### ISSUE TITLE
Real task

### ISSUE THREAD

**Issue by limelect** [CleverComponents/Task-Runner#1]
Can you put a REAL TASK with ALL or MOST options?

**Comment by sergshirokov** [comment]
https://github.com/CleverComponents/Task-Runner/blob/master/Examples/BuildDelphiProject.job

This example shows how to use the following jobs: Command Batch, Parameters, Delphi Scripter, and Call Job. The resulting job defines a set of parameters, such as source and destination paths, compiles a Delphi project, and archives the resulting executable with the pkzipc utility.

The upcoming video tutorial will be available on our YouTube channel: https://www.youtube.com/channel/UC9Si4WNQVSeXQMjdEJ8j1fg
